config/routes.rb
Rails.application.routes.draw do
  patch 'users/update_profile'
  get 'users/account'
  get 'users/profile'
  get 'hotels/index'
  get 'hotels/search'
  get 'hotels/posts'
  devise_for :users
  root 'top#index'
  get 'top/index'
  resources :hotels
  resources :reservations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations
  has_many :hotels, through: :reservations
  has_many :hotels, foreign_key: 'owner_id'
  has_one_attached :image
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def account
  end

  def profile
    @user = current_user
  end

  def update_profile
    @user = current_user
    if @user.update(params.require(:user).permit(:image, :name, :introduction))
      flash[:notice] = "ユーザーIDが「#{@user.id}」の情報を更新しました"
      redirect_to users_profile_path
    else
      render users_profile_path
    end

  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<div class='account-preview'>
  <div class='navigation' >
    <%= link_to "アカウント", users_account_path %>
    <%= link_to "プロフィール", users_profile_path %>
  </div>
  <div class='account-info'>
    <h5>アカウント</h5>
    <table>
      <tr>
        <th>
          メールアドレス
        </th>
        <td>
          <%= current_user.email %>
        </td>
      </tr>
        <th>
          パスワード
        </th>
        <td>
          *********
        </td>
    </table>
    <%= link_to "編集", edit_user_registration_path %>
  </div>
</div>

app/views/users/profile.html.erb
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>
<div class='profile-preview'>
  <div class='navigation' >
    <%= link_to "アカウント", users_account_path %>
    <%= link_to "プロフィール", users_profile_path %>
  </div>
  <div class='edit-profile'>
    <h5>プロフィール</h5>
    <% if current_user.image.attached? %>
      <%= image_tag current_user.image %>
    <% else %>
      <%= image_tag 'default_user_icon.jpg' %>
    <% end %>

    <%= form_with model: @user, url: users_update_profile_path do |f| %>
      <table>
        <tr>
          <th>
            <%= f.label :image, "アイコン画像" %>
            <small>必須</small>
          </th>
          <td>
            <%= f.file_field :image, required: !current_user.image.attached?, class: 'input-area' %>
          </td>
        </tr>

        <tr>
          <th>
            <%= f.label :name, "名前" %>
            <small>必須</small>
          </th>
          <td>
            <%= f.text_field :name, required: true, class: 'input-area' %>
          </td>
        </tr>

        <tr>
          <th>
            <%= f.label :introduction, "自己紹介" %>
            <small>必須</small>
          </th>
          <td>
            <%= f.text_area :introduction, required: true, class: 'input-area' %>
          </td>
        </tr>
      </table>

      <div class="actions">
        <%= f.submit "更新", class: 'submit-button' %>
      </div>

    <% end %>
  </div>
</div>