config/routes.rb
Rails.application.routes.draw do
  patch 'users/update_profile'
  get 'users/account'
  get 'users/profile'
  get 'hotels/index'
  get 'hotels/search'
  get 'hotels/posts'
  devise_for :users
  root 'top#index'
  get 'top/index'
  resources :hotels
  resources :reservations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_one_attached :image
  has_many :reservations
  has_many :users, through: :reservations
  belongs_to :user, foreign_key: 'owner_id'
  validates :name, presence: true
  validates :comment, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :image, presence: true
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def index
  end

  def search
    @hotels = Hotel.where("address LIKE ? AND comment LIKE ?", "%#{params[:area]}%", "%#{params[:keyword]}%")
  end

  def posts
    @hotels = current_user.hotels
  end

  def new
    @hotel = Hotel.new
  end

  def create
    @hotel = Hotel.new(params.require(:hotel).permit(:name, :comment, :price, :address, :image, :owner_id))
    if @hotel.save
      flash[:notice] = "ホテルを登録しました"
      redirect_to @hotel
    else
      render "new"
    end
  end

  def show
    @hotel = Hotel.find(params[:id])
    @reservation = Reservation.new
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/index.html.erb
<h1>Hotels#index</h1>
<p>Find me in app/views/hotels/index.html.erb</p>

app/views/hotels/new.html.erb
<% if @hotel.errors.any? %>
  <% @hotel.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>
<div class='hotel-new-form'>
  <h3>ホテル情報登録</h3>

  <%= form_with model: @hotel do |f| %>
    
    <div>
      <%= f.hidden_field :owner_id, value: current_user.id %>
    </div>

    <table>
      <tr>
        <th>
          <%= f.label :name ,"ホテル名" %>
          <small>必須</small>
        </th>
        <td>
          <%= f.text_field :name, required: true, class: 'input-area' %>
        </td>
      </tr>
      <tr>
        <th class="hotel-new-th">
          <%= f.label :comment ,"ホテル紹介" %>
          <small>必須</small>
        </th>
        <td>
          <%= f.text_area :comment, required: true, class: 'input-area' %>
        </td>
      </tr>
      <tr>
        <th class="hotel-new-th">
          <%= f.label :price ,"料金" %>
          <small>必須</small>
        </th>
        <td>
          <%= f.number_field :price, required: true, in: 1..1000000, class: 'input-area' %>
        </td>
      </tr>
      <tr>
        <th class="hotel-new-th">
          <%= f.label :address ,"住所" %>
          <small>必須</small>
        </th>
        <td>
          <%= f.text_field :address, class: 'input-area' %>
        </td>
      </tr>
      <tr>
        <th class="hotel-new-th">
          <%= f.label :image ,"ルーム画像" %>
          <small>必須</small>
        </th>
        <td>
          <%= f.file_field :image, class: 'input-area' %>
        </td>
      </tr>
    </table>
    <div>
      <%= f.submit "登録", class: 'register-button' %>
    </div>

  <% end %>
</div>

app/views/hotels/posts.html.erb
<h3>登録済みホテル一覧</h3>

<table class='hotels-table'>
  <thead>
    <tr>
      <th>ホテル画像</th>
      <th>ホテル名</th>
      <th>ホテル紹介</th>
      <th>料金</th>
      <th>作成日</th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td>
          <% if hotel.image.attached? %>
            <%= link_to image_tag(hotel.image, class: 'hotel-picture'), hotel %>
          <% else %>
            <%= link_to image_tag('default_room_icon.jpg', class: 'hotel-picture'), hotel %>
          <% end %>
        </td>
        <td><%= link_to hotel.name, hotel %></td>
        <td><%= hotel.comment %></td>
        <td><%= "¥#{hotel.price}" %></td>
        <td><%= hotel.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/hotels/search.html.erb
<h2>検索結果:<%= @hotels.count %>件</h2>
<table class='hotels-table'>
  <thead>
    <tr>
      <th>ホテル画像</th>
      <th>ホテル名</th>
      <th>住所</th>
      <th>料金</th>
    </tr>
  </thead>
  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td>
          <% if hotel.image.attached? %>
            <%= link_to image_tag(hotel.image, class: 'hotel-picture'), hotel %>
          <% else %>
            <%= link_to image_tag('default_room_icon.jpg', class: 'hotel-picture'), hotel %>
          <% end %>
        </td>
        <td><%= hotel.name %></td>
        <td><%= hotel.address %></td>
        <td><%= "¥#{hotel.price}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/hotels/show.html.erb
<div class="hotel-detail">
  <div class="hotel-info">  
    <% if @hotel.image.attached? %>
      <%= link_to image_tag(@hotel.image, class: 'hotel-picture'), @hotel %>
    <% else %>
      <%= link_to image_tag('default_room_icon.jpg', class: 'hotel-picture'), @hotel %>
    <% end %>
    <div class="row" >
      <% if @hotel.user.image.attached? %>
        <%= image_tag @hotel.user.image, class: 'owner-icon' %>
      <% else %>
        <%= image_tag 'default_user_icon.jpg', class: 'owner-icon' %>
      <% end %>
      <div>
        <p><%= @hotel.name %></p>
        <p><%= @hotel.address %></p>
      </div>
    </div>
    <p class="comment" ><%= @hotel.comment %></p>
  </div>
  <div class="reservation-form">
    <%= form_with model: @reservation,url: new_reservation_path, method: :get do |f| %>
      <h5><%= "¥ #{@hotel.price} / 日" %></h5>
      <table>
        <tr>
          <th>
            <%= f.label :start, "開始日" %>
            <small>必須</small>
          </th>
          <td>
            <%= f.date_field :start, required: true, class: 'input-area' %>
          </td>
        </tr>
        <tr>
          <th>
            <%= f.label :end, "終了日" %>
            <small>必須</small>
          </th>
          <td>
            <%= f.date_field :end, required: true, class: 'input-area' %>
          </td>
        </tr>
        <tr>
          <th>
            <%= f.label :number_of_people, "人数" %>
            <small>必須</small>
          </th>
          <td>
            <%= f.number_field :number_of_people, in: 1..10, required: true, class: 'input-area' %>
          </td>
        </tr>
      <%= f.hidden_field :hotel_id, value: @hotel.id %>
      </table>
      <%= f.submit "予約する", class: 'reserve-button' %>
    <% end %>
  </div>
</div>