config/routes.rb
Rails.application.routes.draw do
  patch 'users/update_profile'
  get 'users/account'
  get 'users/profile'
  get 'hotels/index'
  get 'hotels/search'
  get 'hotels/posts'
  devise_for :users
  root 'top#index'
  get 'top/index'
  resources :hotels
  resources :reservations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PotepanRailsReservation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Sevillana&display=swap" rel="stylesheet">
    <style> @import url('https://fonts.googleapis.com/css2?family=Sevillana&display=swap'); </style>
  </head>

  <body>
    <header>
      <div class="left-menu">
        <div><%= link_to "Hotel Booking", root_path, class: 'logo' %></div>
        <%= form_with url: hotels_search_path, method: :get do |f|%>
          <%= f.text_field :area, placeholder: 'エリア' %>
          <%= f.text_field :keyword, placeholder: 'キーワード' %>
          <%= f.submit class: 'search-button' %>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <div class="right-menu">
          <div class="user-name"><%= current_user.name %></div>
          <details>
            <summary> 
              <% if current_user.image.attached? %>
                <%= image_tag current_user.image %>
              <% else %>
                <%= image_tag 'default_user_icon.jpg' %>
              <% end %>
            </summary>
            <div class="user-menu">
              <li><%= link_to "ルーム登録", new_hotel_path %></li>
              <li><%= link_to "予約済みルーム一覧", reservations_path %></li>
              <li><%= link_to "登録済みルーム一覧", hotels_posts_path %></li>
              <li><%= link_to "設定", users_account_path %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            </div>
          </details>
        </div>
      <% else %>
        <div class="right-menu">
          <%= link_to "ログイン", new_user_session_path, class: 'log-in' %>
          <%= link_to "新規登録", new_user_registration_path, class: 'sign-up' %>
        </div>
      <% end %>
    </header>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>  
    <% end %>
    <%= yield %>
    <footer>
    </footer>
  </body>
</html>